using System.Text.Json;
using SeedForge.Domain;
using SeedForge.Services.YouTube;

namespace SeedForge.Services.Apify
{
    /// <summary>
    /// Orchestrates a single-video fetch: resolves the YouTube id, builds the actor input, calls <see cref="ApifyClient"/>,
    /// and probes the first dataset item defensively (subtitles / transcript / captions / segments) so a drifted actor
    /// shape never throws. The raw item is preserved; only a client-level <see cref="ApifyException"/> is a fetch failure.
    /// </summary>
    public sealed class ApifyIngestionService(ApifyClient client, ILogger<ApifyIngestionService> log) : IApifyIngestionService
    {
        public async Task<IngestedVideo> FetchAsync(string urlOrId, CancellationToken ct = default)
        {
            if (!YouTubeUrl.TryGetVideoId(urlOrId, out var videoId))
            {
                throw new ApifyException($"'{urlOrId}' is not a recognizable YouTube URL or video id.");
            }

            var watchUrl = YouTubeUrl.WatchUrl(videoId);
            var input = new
            {
                startUrls = new[] { new { url = watchUrl } },
                maxResults = 1,
                downloadSubtitles = true,
                subtitlesLanguage = "en",
                subtitlesFormat = "plaintext",
                preferAutoGeneratedSubtitles = true,
            };

            var result = await client.RunSyncGetDatasetItemsAsync(input, ct);
            var root = result.Items;

            // The client throws on a genuine fetch error; an empty dataset is simply "nothing to parse", not a failure.
            if (root.ValueKind != JsonValueKind.Array || root.GetArrayLength() == 0)
            {
                log.LogInformation("Apify returned no dataset item for {VideoId}", videoId);
                return new IngestedVideo(false, null, null, null, string.Empty, result.CostUnits, videoId);
            }

            var item = root[0];
            var rawItemJson = item.GetRawText();
            var text = TryJoinSubtitles(item)
                    ?? TryGetString(item, "transcript")
                    ?? TryGetString(item, "captions")
                    ?? TryGetSegmentsText(item, "segments");
            var hadTranscript = !string.IsNullOrWhiteSpace(text);

            var title = TryGetString(item, "title");
            var channel = TryGetString(item, "channelName")
                       ?? TryGetString(item, "channel")
                       ?? TryGetString(item, "channelUsername");

            // Metadata is free: it comes out of the same raw item. A parse miss must never fail the fetch.
            VideoMetadata? metadata = null;
            try
            {
                metadata = ApifyMetadataParser.TryParse(rawItemJson);
            }
            catch (Exception ex)
            {
                log.LogWarning(ex, "Apify metadata parse failed for {VideoId}; continuing without metadata", videoId);
            }

            log.LogInformation("Apify item for {VideoId}: hadTranscript={HadTranscript}, title={HasTitle}, metadata={HasMetadata}",
                videoId, hadTranscript, title is not null, metadata?.HasAnyValue == true);

            return new IngestedVideo(hadTranscript, text, title, channel, rawItemJson, result.CostUnits, videoId, metadata);
        }

        /// <summary>Joins a <c>subtitles</c> array, accepting either string elements or objects carrying <c>plaintext</c>/<c>text</c>.</summary>
        private static string? TryJoinSubtitles(JsonElement item)
        {
            if (item.ValueKind != JsonValueKind.Object
                || !item.TryGetProperty("subtitles", out var subs)
                || subs.ValueKind != JsonValueKind.Array)
            {
                return null;
            }

            var parts = new List<string>();
            foreach (var el in subs.EnumerateArray())
            {
                var s = el.ValueKind == JsonValueKind.String
                    ? el.GetString()
                    : TryGetString(el, "plaintext") ?? TryGetString(el, "text");
                if (!string.IsNullOrWhiteSpace(s)) parts.Add(s!);
            }

            return Normalize(string.Join("\n", parts));
        }

        /// <summary>Joins a <c>segments</c> array of objects each carrying a <c>text</c> field (or string elements).</summary>
        private static string? TryGetSegmentsText(JsonElement item, string key)
        {
            if (item.ValueKind != JsonValueKind.Object
                || !item.TryGetProperty(key, out var segs)
                || segs.ValueKind != JsonValueKind.Array)
            {
                return null;
            }

            var parts = new List<string>();
            foreach (var el in segs.EnumerateArray())
            {
                var s = el.ValueKind == JsonValueKind.String ? el.GetString() : TryGetString(el, "text");
                if (!string.IsNullOrWhiteSpace(s)) parts.Add(s!);
            }

            return Normalize(string.Join(" ", parts));
        }

        /// <summary>Reads a string property if present and non-empty; never throws on a missing/typed-differently key.</summary>
        private static string? TryGetString(JsonElement item, string key)
        {
            if (item.ValueKind == JsonValueKind.Object
                && item.TryGetProperty(key, out var prop)
                && prop.ValueKind == JsonValueKind.String)
            {
                var s = prop.GetString();
                return string.IsNullOrWhiteSpace(s) ? null : s;
            }
            return null;
        }

        private static string? Normalize(string joined)
        {
            var trimmed = joined.Trim();
            return string.IsNullOrWhiteSpace(trimmed) ? null : trimmed;
        }
    }
}
